---
- name: Ping and Print
  hosts: localhost
  tasks:         
    - name:  Create a directory if it does not exist> /home/luciano/createdbyansible
      ansible.builtin.file:
        path: /home/luciano/createdbyansible
        state: directory
        mode: '0755'

    - name: create a file
      ansible.builtin.file:
        path: /home/luciano/createdbyansible/test_file
        state: touch
      
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/luciano/createdbyansible/test_file
        owner: luciano
        group: luciano
        mode: '0666' 
    - name: Touch the same file, but add/remove some permissions
      ansible.builtin.file:
        path: /home/luciano/createdbyansible/test_file
        state: touch
        mode: u+rw,g-wx,o-rwx
        

    

...
